version: '3'

services:
  spark:
    build: .
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_HOSTNAME=localhost
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    container_name: spark
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "5000:5000"
      - "8118:8118"
    networks:
      - spark-network
    command: >
      bash -c "mkdir -p data/{bronze,silver,gold} & mlflow ui --host 0.0.0.0 --port 8118 & python /app/src/app.py & tail -f /dev/null"

networks:
  spark-network:
    driver: bridge